<?php
$nadpiscz="L-39 Albatros";
$nadpisen="L-39 Albatros";
$obsahcz="<p>Aero L-39 Albatros je štandardné prúdové cvičné lietadlo a je priamym nástupcom predchádzajúceho úspešného typu Aero L-29 Delfín. Prototyp L-39 prvý krát vzlietol 4. novembra 1968 a od roku 1971 bolo lietadlo vyrábané sériovo, ako lietadlo pre základný výcvik vojenských pilotov letectiev Sovietskeho zväzu, Československa a ďalších krajín Varšavského paktu (s výnimkou Poľska, ktoré používalo vlastné lietadlo PZL TS-11 Iskra).</p>
<img src='obrazky/l-39cm.jpg' alt='L-39 CM' />
<p>L-39 Albatros je všestranné lietadlo určené pre základný, pokročilý a bojový letecký výcvik, vo verziách, ktoré umožňujú inštaláciu výzbroje (L-39C, L-39ZO, L-39ZA). Môže byť použité ako ľahké bojové lietadlo, a obmedzene môže pôsobiť aj proti vzdušným cieľom. Vďaka skvelým letovým vlastnostiam a ľahkej ovládateľnosti je vhodné i pre leteckú akrobaciu, ktorú s týmto typom predvádzala napr. slovenská akrobatická skupina <a href=\"http://www.bielealbatrosy.sk\" title=\"web skupiny Biele Albatrosy\">Biele Albatrosy</a> (1991-2004), ruská skupina Rusi z Vjazmy, alebo francúzsky Breitling Jet Team. Medzi jeho ďalšie prednosti patrí vysoká spoľahlivosť, jednoduchosť a nenáročnosť na obsluhu. Lietadlo je navrhnuté tak, aby mohlo pôsobiť bez problémov aj z nespevnených plôch (vstupy vzduchu vysoko nad zemou, kryté pred nečistotami krídlom, zakryté podvozkové šachty).</p><p><a href=\"index.php?page=about\" title=\"informácie o našom tíme\">Náš tím</a> používa modernizovanú cvičnú verziu L-39CM.</p>";

$obsahen="<p>Aero L-39 Albatros is standard jet trainer aircraft developed as a&nbsp;successor of previously successful model Aero L-29 Delfín. The first take off of the prototype of L-39 took place at 4th November 1968 and serial production started 1971. Since that it has been used for basic training of military aviators of Soviet Union, Czechoslovakia and other Warszaw pact's air forces (with exception of Polish Air force which had been using home produced PZL TS-11 Iskra).</p>
<img src='obrazky/l-39cm.jpg' alt='L-39 CM' />
<p>L-39 Albatros is multirole aircraft dedicated to basic, advanced and combat flight training. Versions that can carry various ordnance (L-39C, L-39ZO, L-39ZA) can also be used as light combat aircraft with limited air to air capabilities. Thanks to excellent flight characteristics and easy maneuverability is this plane also suitable for aerobatics and as such has also been used by several groups - e.g. slovak <a href=\"http://www.bielealbatrosy.sk\" title=\"website of Biele Albatrosy group\">The Biele albatrosy aerobatics group</a> (1991-2004), russian The Rusi z vjazmy group or french The Breitling Jet Team. Among other qualities are also high reliability, simplicity and modest maintenance. The plane has been designed to operate from unpaved runways (air intakes shieleded from mud by wings, covered gear bays).</p><p><a href=\"index.php?page=about\" title=\"information about our team\">Our team</a> uses modernized standard training version - <br />L-39CM</p>
";
?>